In [15]:
import numpy as np

In [19]:
# matrix given
x = np.array([[1, 0.2, 0.5], [0.2, 1, 0.8], [0.5, 0.8, 1]])

In [20]:
# finding the inverse of a matrix
inverse = np.linalg.inv(x)
print(f'The inversion of x = {inverse}')

The inversion of x = [[ 1.56521739  0.86956522 -1.47826087]
 [ 0.86956522  3.26086957 -3.04347826]
 [-1.47826087 -3.04347826  4.17391304]]


In [21]:
# getting the transpose
transpose=np.transpose(x)
print(f'The transpose of x = {transpose}')

The transpose of x = [[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


In [22]:
# finding the determinant
determinant = np.linalg.det(x)
print(f'The determinant of x = {determinant}')

The determinant of x = 0.2299999999999999


In [23]:

scalar = 7
new_transformation = scalar *x
print(f'Transformation = {new_transformation}')

Transformation = [[7.  1.4 3.5]
 [1.4 7.  5.6]
 [3.5 5.6 7. ]]
